version: 2.1
orbs:
    gh: circleci/github-cli@1.0.3
jobs:
    build:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - run:
                  name: Verify Artifacts
                  command: yarn test

    publish:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            -   attach_workspace:
                    at: .
            -   run:
                    name: Authenticate with registry
                    command: |
                        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                        echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            -   run:
                    name: Publish @brightlayer-ui/storybook-themes
                    command:  |
                        yarn publish:package -b $CIRCLE_BRANCH

    tag:
        docker:
            -   image: cimg/node:14.19.0-browsers
        steps:
            -   checkout
            -   gh/setup
            -   attach_workspace:
                    at: .
            -   run:
                    name: Tag @brightlayer-ui/storybook-themes
                    command:  |
                        yarn tag:package -b $CIRCLE_BRANCH -s -blui-storybook-themes

workflows:
    version: 2
    themes:
        jobs:
            - build
            - publish:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                              - dev
            - tag:
                  requires:
                      - publish
                  filters:
                      branches:
                          only:
                              - master
